language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28

script: ./gradlew check

notifications:
  email: false
  slack:
    rooms:
      secure: CcmbFrv/r055iiwjjqWK6qa2KdgZqBAGz2Y7IR0O2syV5ESeMoV5ID1XwFGvEvyf2K5aq9x1kvBgaphvxiowTZlcRlTYTMi63XPYKE0PtLb6DTuoLW1vjK2AW90+5uo4KKX2KnHaHVbJ5NSNdUwyWkHxR3jGmTSD2QzSBdr6E6FNgLWwN4WiaK4m0oH0eS1M1+ZbsDvXI0iHXKZF+TVQa6RLOG6TqFCeSlshhsBcPkz/4uG/kTmQwBQbOq4P94PQetwuMYNw+pmytIx1EWLzpOIRVBEoQJGFkCbTrjwhRDI8GYqmpoy798GxKIzyaHjIHN+rrzv53aqjUKFkC4OvrW2nr7cFE6b4m0sUN6/W2bma4y86Pg7oYLN9aTMjgE1/tIMjd7QYeFQWNKrv0lKm27sCSI4QkH6OuJl6U8WxelEiq0A0Of+fqkkeJ2DYbz7icUkUQiNeC2ia6X2A4ybEdgcvtftoEJBUOUII+QxN8C2MwJ4MT9tsV+0Ce+X6Sg+0baANtL6EqAvw0rf60SHZosTeg24Em4Buyu2fg19S4AL3wtrXVItHw7L39/iw6F/AihJUt9QuEiYoYLvVr2yGb7i7xdKNB94fVTR7gLXREIjb6Xk7Bt2BEBaO0mbQ4LLQ15OprILcgOt2LJqwEmkiNLhPZer74u6RFp0Qy2dq3Iw=
    on_success: change
