language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-26

script:
  - ./gradlew ktlint
  - ./gradlew test

notifications:
  email: false
  slack:
    rooms:
      secure: H/Z/DerTVIRh7K+dsxe4Fhp3G+qChBli+k7Ix7KA6o9s2hHo0QBFx3GN9yCglx2CEMLWx263plWqbYgmnXaSBKIyv/WwkSEZz90tjBCp4s1RZF7Usu0+FpYvr2z7wS7tiJfKeOMkiNBrPaXiZuXWQt+3tZ91oKeIMFuYGR9bVJotrD8uNUZk3yFSHUelKra2JsGyCysNmBuXCQO3mVCG7xlnbv0jKD/XgBE18Spra1NqGYFHqn2krRJAovhpI2TEOWvEnmmygP5W9YKRr9Iz7N2dcKEfu5+E7CTgSSv8dNZM24B5l0IV/zNcBtxsiWG9NlmEYchfl8nPw5hyAPyBVHJy5nUPPE0abjbtIoOFzxBQrwJdpufi4BrDbi4eLtEgaEJOvWGMUpbu92SPqVDt3DMdBo8Nd+zW8zs3BcW/XJIZbyI/wVSYgbJ4qfmxUMz2iERFljma8uOHI0xWFNihksbsPqH1AcZQMRqv/v83hpFX9X6hPsJHC9oMrM8KSPgygZe4zhB/saqw93JCPWR8oz0gyaSHiiHZSIQANWnAHeMqGv197f9+VhRIfDwB1oGkeekrt+z0v0mmgCuIVolwclxo/9KdU38tRjuPkNrvoyvfE7HIVuMzYnI+U5iWX/D53LD9KLGq0q2RTpQ4TJ28E0pFrkYnu+fNAnYdqfOHmEw=
    on_success: change
